---
- name: Setup all my servers on AWS
  hosts: web
  vars:
    django_archive: dist/malickosti-v-akvarelkach-0.0.1.tar.gz
    django_config_file: local_settings.j2
    django_config: malickosti.settings
    django_project_name: 'cz-terkyakvarelky'
    django_project_environment: '{{ lookup("env", "DJANGO_PROJECT_ENVIRONMENT") }}'
    django_wsgi_file: malickosti/wsgi.py

  roles:
    - role: practical-ansible.nginx-django
    - role: practical-ansible.nginx-redirect
      nginx_redirect_project_name: cz-terkyakvarelky
      nginx_redirect_server_name: www.terkyakvarelky.cz
      nginx_redirect_destination_url: https://terkyakvarelky.cz
      nginx_redirect_status: 301

  post_tasks:
    - name: Configure Transaction cron job
      cron:
        name: 'Pair cz-terkyakvarelky transactions'
        minute: 0,30
        job: 'cd /var/www/cz-terkyakvarelky/{{django_project_environment}}/current && cd /var/www/cz-terkyakvarelky/{{django_project_environment}}/virtualenv/bin/python /var/www/cz-terkyakvarelky/{{django_project_environment}}/current/manage.py pairtransactions'
