# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import web.models.visibility


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('description', models.TextField(help_text='field-description-help-text')),
                ('price', models.PositiveIntegerField(default=0, help_text='field-method-price-help-text', verbose_name='field-price')),
                ('weight', models.PositiveIntegerField(default=0, help_text='field-weight-help-text', verbose_name='field-weight')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
            ],
            options={
                'verbose_name': 'Delivery Method',
                'verbose_name_plural': 'Delivery Methods',
            },
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('status', models.PositiveIntegerField(choices=[(1, 'status-for-sale'), (2, 'status-reserved'), (3, 'status-sold')], default=1, verbose_name='field-drawing-status')),
                ('image', models.ImageField(height_field='image_height', upload_to='var/drawings', verbose_name='field-drawing-image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('image_width', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
            },
        ),
        migrations.CreateModel(
            name='DrawingPriceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('price', models.PositiveIntegerField(help_text='field-method-price-help-text', verbose_name='field-price')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='field-valid-from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='field-valid-until')),
            ],
            options={
                'verbose_name': 'Drawing Price Level',
                'verbose_name_plural': 'Drawing Price Levels',
            },
        ),
        migrations.CreateModel(
            name='DrawingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.PositiveIntegerField(choices=[(1, 'relationship-different-size'), (2, 'relationship-duplicate')])),
                ('child', models.ForeignKey(help_text='field-drawing-parent-help-text', on_delete=django.db.models.deletion.CASCADE, related_name='drawings_parent', to='web.Drawing', verbose_name='field-drawing-parent')),
                ('parent', models.ForeignKey(help_text='field-drawing-child-help-text', on_delete=django.db.models.deletion.CASCADE, related_name='drawings_child', to='web.Drawing', verbose_name='field-drawing-child')),
            ],
            options={
                'verbose_name': 'Drawing Relationship',
                'verbose_name_plural': 'Drawing Relationships',
            },
        ),
        migrations.CreateModel(
            name='DrawingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('size_horizontal', models.PositiveIntegerField(help_text='field-size-horizontal-help-text', verbose_name='field-size-horizontal')),
                ('size_vertical', models.PositiveIntegerField(help_text='field-size-vertical-help-text', verbose_name='field-size-vertical')),
            ],
            options={
                'verbose_name': 'Drawing Size',
                'verbose_name_plural': 'Drawing Sizes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('event_type', models.PositiveIntegerField(choices=[(1, 'type-exposition'), (2, 'type-vernissage')], default=1, verbose_name='Type')),
                ('start', models.DateTimeField(verbose_name='field-start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='field-end')),
                ('all_day', models.BooleanField(default=False, help_text='field-all-day-help-text', verbose_name='field-all-day')),
                ('description', models.TextField(help_text='field-description-help-text')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('address', models.CharField(help_text='field-address-help-text', max_length=255)),
                ('website', models.URLField(help_text='field-website-help-text')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('buyer', models.CharField(help_text='field-buyer-help-text', max_length=255, verbose_name='field-buyer')),
                ('email', models.EmailField(max_length=254, verbose_name='field-email')),
                ('phone', models.CharField(max_length=63, verbose_name='field-phone')),
                ('address', models.CharField(help_text='field-address-help-text', max_length=63, verbose_name='field-address')),
                ('price', models.PositiveIntegerField(verbose_name='field-price')),
                ('paid', models.BooleanField(default=False, verbose_name='field-paid')),
                ('over_paid', models.BooleanField(default=False, verbose_name='field-over-paid')),
                ('symvar', models.CharField(blank=True, max_length=63, unique=True, verbose_name='field-symvar')),
                ('status', models.PositiveIntegerField(choices=[(1, 'status-new'), (2, 'status-confirmed'), (3, 'status-on-route'), (4, 'status-delivered'), (5, 'status-canceled')], default=1, verbose_name='field-status')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.DeliveryMethod', verbose_name='field-delivery-method')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='web.Drawing')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ident', models.CharField(blank=True, help_text='field-payment-ident-help-text', max_length=255, null=True, verbose_name='field-payment-ident')),
                ('symvar', models.CharField(blank=True, max_length=255, null=True, verbose_name='field-symvar')),
                ('symcon', models.CharField(blank=True, max_length=255, null=True, verbose_name='field-symcon')),
                ('symspc', models.CharField(blank=True, max_length=255, null=True, verbose_name='field-symspc')),
                ('amount', models.CharField(max_length=255, verbose_name='field-amount')),
                ('sender', models.CharField(blank=True, default='unknown', help_text='field-payment-sender-help-text', max_length=255, verbose_name='field-payment-sender')),
                ('bank', models.CharField(blank=True, default='unknown', max_length=255, verbose_name='Bank')),
                ('currency', models.CharField(blank=True, default='unknown', max_length=255, verbose_name='field-currency')),
                ('received_at', models.DateTimeField(blank=True, help_text='field-received-at-help-text', null=True, verbose_name='field-received-at')),
                ('message', models.TextField(blank=True, max_length=255, null=True, verbose_name='field-message')),
                ('status', models.PositiveIntegerField(choices=[(1, 'status-in-progress'), (2, 'status-paid'), (3, 'status-canceled')], default=2, verbose_name='field-status')),
                ('user_identification', models.CharField(blank=True, help_text='field-user-identification-help-text', max_length=255, null=True, verbose_name='field-user-identification')),
                ('order', models.ForeignKey(blank=True, help_text='Which order is this payment related to?', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='web.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('description', models.TextField(help_text='field-description-help-text')),
                ('needs_account_info', models.BooleanField(default=False, help_text='field-payment-method-need-account-info-help-text')),
                ('price', models.PositiveIntegerField(default=0, help_text='field-method-price-help-text', verbose_name='field-price')),
                ('weight', models.PositiveIntegerField(default=0, help_text='field-weight-help-text', verbose_name='field-weight')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='TextAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('text', models.TextField(help_text='field-text-help-text')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
                ('weight', models.PositiveIntegerField(default=0, help_text='field-weight-help-text', verbose_name='field-weight')),
            ],
            options={
                'verbose_name': 'Text about',
                'verbose_name_plural': 'Texts about',
            },
        ),
        migrations.CreateModel(
            name='TextConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('text', models.TextField(help_text='field-text-help-text')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
                ('weight', models.PositiveIntegerField(default=0, help_text='field-weight-help-text', verbose_name='field-weight')),
            ],
            options={
                'verbose_name': 'Trade Conditions',
                'verbose_name_plural': 'Trade Conditions',
            },
        ),
        migrations.CreateModel(
            name='TextPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(height_field='height', upload_to='var/texts', verbose_name='field-image', width_field='width')),
                ('height', models.PositiveIntegerField(null=True)),
                ('width', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True, help_text='field-text-help-text', null=True)),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('textphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.TextPhoto')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.textphoto',),
        ),
        migrations.CreateModel(
            name='TextAboutPhoto',
            fields=[
                ('textphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.TextPhoto')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.TextAbout')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.textphoto',),
        ),
        migrations.CreateModel(
            name='TextConditionsPhoto',
            fields=[
                ('textphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.TextPhoto')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.TextConditions')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.textphoto',),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.PaymentMethod', verbose_name='field-payment-method'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Location'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='price_levels',
            field=models.ManyToManyField(to='web.DrawingPriceLevel', verbose_name='field-price-levels'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='web.DrawingSize', verbose_name='field-size'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='payment_methods',
            field=models.ManyToManyField(to='web.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.Event'),
        ),
    ]
