# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import web.models.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('text', models.TextField(help_text='field-text-help-text')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'visibility-public'), (2, 'visibility-private')], default=1, verbose_name='field-visibility')),
                ('weight', models.PositiveIntegerField(default=0, help_text='field-weight-help-text', verbose_name='field-weight')),
            ],
            options={
                'verbose_name': 'Text Contact',
                'verbose_name_plural': 'Texts Contact',
            },
        ),
        migrations.CreateModel(
            name='TextContactPhoto',
            fields=[
                ('textphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.TextPhoto')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.TextContact')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.textphoto',),
        ),
    ]
