# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='payment_methods',
            field=models.ManyToManyField(to='web.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='deliverymethod',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='More weight, more priority'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='More weight, more priority'),
        ),
    ]
