# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import web.models.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Very short description that helps to recognize the object', max_length=255)),
                ('text', models.TextField(help_text='You can format the text in Markdown')),
                ('visibility', web.models.visibility.VisibilityField(choices=[(1, 'Public'), (2, 'Hidden')], default=1)),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trade Conditions',
                'verbose_name_plural': 'Trade Conditions',
            },
        ),
        migrations.CreateModel(
            name='TextConditionsPhoto',
            fields=[
                ('textphoto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web.TextPhoto')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.TextConditions')),
            ],
            options={
                'abstract': False,
            },
            bases=('web.textphoto',),
        ),
    ]
