# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:05
from __future__ import unicode_literals

from django.db import migrations
import web.models.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170906_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='visibility',
            field=web.models.visibility.VisibilityField(choices=[(1, 'Public'), (2, 'Hidden')], default=1),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='visibility',
            field=web.models.visibility.VisibilityField(choices=[(1, 'Public'), (2, 'Hidden')], default=1),
        ),
    ]
