# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_textconditions_textconditionsphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textconditions',
            name='name',
            field=models.CharField(default='Obchodní podmínky', help_text='Very short description that helps to recognize the object', max_length=255),
        ),
    ]
