# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170907_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
