# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(height_field='image_height', upload_to='var/drawings', verbose_name='Image of drawing', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='textaboutphoto',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.TextAbout'),
        ),
        migrations.AlterField(
            model_name='textconditions',
            name='name',
            field=models.CharField(help_text='Very short description that helps to recognize the object', max_length=255),
        ),
        migrations.AlterField(
            model_name='textconditionsphoto',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.TextConditions'),
        ),
    ]
