# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 06:30
from __future__ import unicode_literals

from django.db import migrations
import web.models.visibility


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171004_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=web.models.visibility.VisibilityField(choices=[(1, 'Public'), (2, 'Hidden')], default=1),
        ),
    ]
