# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_order_price'),
        ('web', '0006_event_all_day'),
    ]

    operations = [
    ]
