# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_paymentmethod_needs_account_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symvar',
            field=models.CharField(blank=True, max_length=63, unique=True, verbose_name='Variable symbol'),
        ),
    ]
