# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20171007_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='ident',
            field=models.CharField(blank=True, help_text='Payment identificator, usually generated by the bank', max_length=255, null=True, verbose_name='Identificator'),
        ),
    ]
