# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('status', models.PositiveIntegerField(choices=[(1, 'status-for-sale'), (2, 'status-reserved'), (3, 'status-sold')], default=1, verbose_name='field-drawing-status')),
                ('image', models.ImageField(height_field='image_height', upload_to='var/drawings', verbose_name='field-drawing-image', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(null=True)),
                ('image_width', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
            },
        ),
        migrations.CreateModel(
            name='DrawingRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.PositiveIntegerField(choices=[(1, 'relationship-different-size'), (2, 'relationship-duplicate')])),
                ('child', models.ForeignKey(help_text='field-drawing-parent-help-text', on_delete=django.db.models.deletion.CASCADE, related_name='drawings_parent', to='drawings.Drawing', verbose_name='field-drawing-parent')),
                ('parent', models.ForeignKey(help_text='field-drawing-child-help-text', on_delete=django.db.models.deletion.CASCADE, related_name='drawings_child', to='drawings.Drawing', verbose_name='field-drawing-child')),
            ],
            options={
                'verbose_name': 'Drawing Relationship',
                'verbose_name_plural': 'Drawing Relationships',
            },
        ),
        migrations.CreateModel(
            name='DrawingSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
                ('size_horizontal', models.PositiveIntegerField(help_text='field-size-horizontal-help-text', verbose_name='field-size-horizontal')),
                ('size_vertical', models.PositiveIntegerField(help_text='field-size-vertical-help-text', verbose_name='field-size-vertical')),
            ],
            options={
                'verbose_name': 'Drawing Size',
                'verbose_name_plural': 'Drawing Sizes',
            },
        ),
        migrations.CreateModel(
            name='DrawingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='field-name-help-text', max_length=255, verbose_name='field-name')),
            ],
            options={
                'verbose_name': 'Drawing Tag',
                'verbose_name_plural': 'Drawing Tags',
            },
        ),
        migrations.AddField(
            model_name='drawing',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='drawings.DrawingSize', verbose_name='field-size'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='tags',
            field=models.ManyToManyField(related_name='drawings', to='drawings.DrawingTag', verbose_name='field-tags'),
        ),
    ]
