# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingsize',
            name='standalone_name',
            field=models.BooleanField(default=False, help_text='field-standalone-name-help-text', verbose_name='field-standalone-name'),
        ),
    ]
