# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelevel',
            name='drawings',
            field=models.ManyToManyField(related_name='price_levels', to='drawings.Drawing', verbose_name='field-price-levels'),
        ),
    ]
