# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20171020_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelevel',
            name='drawings',
            field=models.ManyToManyField(blank=True, related_name='price_levels', to='drawings.Drawing', verbose_name='field-drawings'),
        ),
    ]
